pipeline {
    agent any
    parameters{
        choice(name: "BRANCH",
            choices: "\nmaster")
        choice(name: "ACTION",
            choices: "\ndeploy")
    }

    stages {
        stage ("Github checkout") {
            steps {
                git branch: "${params.BRANCH}", url: "https://github.com/kunalnanda/ops-technical-test.git", credentialsId: "73d9b05d-84a7-4622-bd32-8738b59bb858"
            }
        }
        stage ("Stage 1 - Install python") {
            steps {
                sh """
                    sudo yum install python python-pip -y
                    pip install --upgrade pip
                    pip install Flask
                    pip install flask-restful
                    pip install healthcheck
                """
            }
        }

        stage ("Stage 2 - Stop any previous running application") {
            steps {
                withEnv(['JENKINS_NODE_COOKIE=dontkill']) {
                    sh """
                        set +e
                        kill \$(ps aux | grep '[p]ython2.7 ./app.py' | awk '{print \$2}')
                    """
                }
            }
        }

        stage ("Stage 3 - Deploy application") {
            when {
                expression { params.ACTION == "deploy" }
            }
            steps {
                withEnv(['JENKINS_NODE_COOKIE=dontkill']) {
                    sh """
                        set +e
                        mkdir myob
                        cd myob
                        tar -zxvf ../myob_test.tar.gz
                        set -e
                        cd app
                        nohup ./app.py &
                    """
                }
            }
        }
    }
}